1
#1.a
vector_1 <- -5:5
vector_1

#[1] -5 -4 -3 -2 -1  0  1  2  3  4  5




#1.b
x <- 1:7
x

#[1] 1 2 3 4 5 6 7


2
vector_2 <- seq(1, 3, by=0.2)
vector_2

#[1] 1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 2.8 3.0


3
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 
          27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 
          17, 37, 43, 53, 41, 51, 35, 24, 33, 41, 53, 40, 
          18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 
          26, 18)

#3.a
ages[3]

#[1] 22



#3.b
ages[c(2, 4)]

#[1] 28 36



#3.c
ages[-c(4, 12)]

#[1] 34 28 22 27 18 52 39 42 29 35 27 22 37 34 19 20 57 49 50 37 46 25 17 37 43 53 41 51 35 24
#[31] 33 41 53 40 18 44 38 41 48 27 39 19 30 61 54 58 26 18



4
x <- c("first"=3, "second"=0, "third"=9)

#4.a
x[c("first", "third")]

#first third 
#    3     9 


#4.b
names(x)

#[1] "first"  "second" "third"

#The first output shows the entire vector, displaying the names alongside their values.
#The second output shows a subset of the vector, specifically the values of "first" and "third". The named output retains the names, making it clear which values are being referenced.



5
x <- -3:2

#5.a
x[2] <- 0
x

#[1] -3  0 -1  0  1  2

#The initial sequence starts at -3 and ends at 2, with consecutive integers.
#After modifying the second element (originally -2) to 0, the sequence now has 0 in the second position. The other elements remain unchanged.


6
#6.a
cruz_data <- data.frame(
  Month = c("Jan", "Feb", "March", "Apr", "May", "June"),
  Price_per_liter = c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00),
  Purchase_quantity = c(25, 30, 40, 50, 10, 45)
)
cruz_data

#  Month Price_per_liter Purchase_quantity
#1   Jan           52.50                25
#2   Feb           57.25                30
#3 March           60.00                40
#4   Apr           65.00                50
#5   May           74.25                10
#6  June           54.00                45




#6.b
cruz_data$Total_expenditure <- cruz_data$Price_per_liter * cruz_data$Purchase_quantity

average_expenditure <- weighted.mean(cruz_data$Total_expenditure, cruz_data$Purchase_quantity)

average_expenditure

#[1] 2298.062



7
data("rivers")
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers),
          var(rivers), sd(rivers), min(rivers), max(rivers))
data

#[1]    141.0000  83357.0000    591.1844    425.0000 243908.4086    493.8708    135.0000
#[8]   3710.0000



8
#8.a
power_ranking <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 
                   14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
celebrity_name <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", 
                    "U2", "Tiger Woods", "Steven Spielberg", 
                    "Howard Stern", "50 Cent", "Cast of the Sopranos", 
                    "Dan Brown", "Bruce Springsteen", "Donald Trump", 
                    "Muhammad Ali", "Paul McCartney", "George Lucas", 
                    "Elton John", "David Letterman", "Phil Mickelson", 
                    "J.K Rowling", "Bradd Pitt", "Peter Jackson", "Dr. 
                    Phil McGraw", "Jay Lenon", "Celine Dion", 
                    "Kobe Bryant")
pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 
         55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)

print(power_ranking)
print(celebrity_name)
print(pay)



#[1] "Tom Cruise"                            "Rolling Stones"                       
# [3] "Oprah Winfrey"                         "U2"                                   
# [5] "Tiger Woods"                           "Steven Spielberg"                     
#[7] "Howard Stern"                          "50 Cent"                              
#[9] "Cast of the Sopranos"                  "Dan Brown"                            
#[11] "Bruce Springsteen"                     "Donald Trump"                         
#[13] "Muhammad Ali"                          "Paul McCartney"                       
#[15] "George Lucas"                          "Elton John"                           
#[17] "David Letterman"                       "Phil Mickelson"                       
#[19] "J.K Rowling"                           "Bradd Pitt"                           
#[21] "Peter Jackson"                         "Dr. \n                    Phil McGraw"
#[23] "Jay Lenon"                             "Celine Dion"                          
#[25] "Kobe Bryant"     



#8.b
power_ranking[19] <- 15
pay[19] <- 90

#[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25


print(power_ranking)
print(pay)


#[1]  67  90 225 110  90 332 302  41  52  88  55  44  55  40 233  34  40  47  75  25  39  45
#[23]  32  40  31

#8.c
power_ranking_data <- data.frame(power_ranking, celebrity_name, pay)
write.csv(power_ranking_data, "PowerRanking.csv", row.names = FALSE)
power_ranking_data <- read.csv("PowerRanking.csv")
print(power_ranking_data)

#   power_ranking                        celebrity_name pay
#1              1                            Tom Cruise  67
#2              2                        Rolling Stones  90
#3              3                         Oprah Winfrey 225
#4              4                                    U2 110
#5              5                           Tiger Woods  90
#6              6                      Steven Spielberg 332
#7              7                          Howard Stern 302
#8              8                               50 Cent  41
#9              9                  Cast of the Sopranos  52
#10            10                             Dan Brown  88
#11            11                     Bruce Springsteen  55
#12            12                          Donald Trump  44
#13            13                          Muhammad Ali  55
#14            14                        Paul McCartney  40
#15            15                          George Lucas 233
#16            16                            Elton John  34
#17            17                       David Letterman  40
#18            18                        Phil Mickelson  47
#19            15                           J.K Rowling  90
#20            20                            Bradd Pitt  25
#21            21                         Peter Jackson  39
#22            22 Dr. \n                    Phil McGraw  45
#23            23                             Jay Lenon  32
#24            24                           Celine Dion  40
#25            25                           Kobe Bryant  31



#8.d
power_ranking_data <- read.csv("PowerRanking.csv")
ranks_data <- power_ranking_data[10:20, ]
print(ranks_data)
save(ranks_data, file = "Ranks.RData")

#Part a: Displays the names, rankings, and pay of the top celebrities.
#Part b: Shows the modified ranking and pay for J.K. Rowling.
#Part c: Displays the imported data from the CSV file, confirming the correct format and values.
#Part d: Creates a subset of rows 10 to 20 from the dataset and saves it as an RData file.

9


install.packages("readxl")

library(readxl)

9
#9.a
file_path <- "C:/Users/ASITSD/Downloads/hotels-vienna.xlsx"

hotels_data <- read_excel(file_path)

print(hotels_data)

#9.b
dim(hotels_data)

#[1] 428 24


#9.c
library(dplyr)
selected_data <- select(hotels_data, country, neighbourhood, 
                        price, stars, accommodation_type, rating)
head(selected_data)


#9.d
save(selected_data, file = "new.RData")

#9.e
load("new.RData")
head(selected_data)
tail(selected_data)

10
vegetable_list <- c("Lettuce", "Potato", "Cabbage", "Eggplant", "Spinach", "Bittergour",
                    "Cucumbers","Bell Peppers", "Lady Finger", "Mushrooms")
print(vegetable_list)

# [1] "Lettuce"      "Potato"       "Cabbage"      "Eggplant"     "Spinach"      "Bittergour"  
#[7] "Cucumbers"    "Bell Peppers" "Lady Finger"  "Mushrooms"   

#10.b
vegetable_list <- c(vegetable_list, "Spinach", "Brocolli")

print(vegetable_list)

#[1] "Lettuce"      "Potato"       "Cabbage"      "Eggplant"     "Spinach"      "Bittergour"
#[7] "Cucumbers"    "Bell Peppers" "Lady Finger"  "Mushrooms"    "Spinach"      "Brocolli"   


#10.c
vegetable_list <- c(vegetable_list[1:5], "Tomato", "Ginger", 
                    "Carrot", "Corn", vegetable_list[6:12])
print(vegetable_list)

# [1] "Lettuce"      "Potato"       "Cabbage"      "Eggplant"     "Tomato"       "Tomato" 
#[7] "Ginger"       "Carrot"       "Corn"         "Ginger"       "Carrot"       "Corn"     
#[13] "Cucumbers"    "Bell Peppers" "Lady Finger"  "Mushrooms"



#10.d
vegetable_list <- vegetable_list[-c(5, 10, 15)]

print(vegetable_list)

#[1] "Lettuce"      "Potato"       "Cabbage"      "Eggplant"     "Tomato"       "Ginger"   
#[7] "Carrot"       "Corn"         "Carrot"       "Corn"         "Cucumbers"    "Bell Peppers"
#[13] "Mushrooms"   
